export const BLOGCHEATKEY_PROFILE = {
  serviceName: "블로그치트키 (BlogCheatKey)",
  description:
    "AI 기반 SEO 최적화 블로그 콘텐츠 자동 생성 SaaS 플랫폼. 자영업자/소상공인이 키워드만 입력하면 AI가 SEO 조건을 충족하는 고품질 블로그 글을 3분 만에 자동 작성.",
  businessType: "AI SaaS 스타트업",
  industry: [
    "AI/ML",
    "콘텐츠테크",
    "마케팅테크",
    "SEO",
    "디지털 마케팅",
  ],
  targetCustomers: "자영업자, 소상공인, 마케터, 블로거",
  techStack: [
    "React",
    "TypeScript",
    "Node.js",
    "PostgreSQL",
    "Claude API",
    "Gemini API",
    "Perplexity API",
  ],
  revenueModel: "구독 기반 SaaS (월 30,000원 ~ 100,000원)",
  stage: "초기 스타트업 / MVP 운영 중",
  relevantKeywords: [
    "AI",
    "인공지능",
    "SaaS",
    "콘텐츠 생성",
    "SEO",
    "자영업자",
    "소상공인",
    "디지털 전환",
    "마케팅 자동화",
    "스타트업",
    "창업",
    "기술개발",
    "클라우드",
    "SW개발",
    "ICT",
    "데이터",
  ],
  supportTypes: [
    "창업 지원 (예비창업패키지, 초기창업패키지, 청년창업사관학교)",
    "AI/기술 R&D (AI 바우처, 데이터 바우처, 기술개발사업)",
    "소상공인 디지털화 (스마트상점, 디지털 전환 지원)",
    "마케팅/판로 (온라인 판로 지원, 수출바우처)",
    "인력 지원 (청년 디지털 일자리, 채용 지원금)",
    "클라우드/인프라 (클라우드 바우처, SW 개발 지원)",
  ],
} as const;
